name: "2021 Black Cannondale Quick 5"
make: "Cannondale"
model: "2021 Cannondale Quick 5"
bike_type: "Hybrid"
serial: "Unspecified"
color: "Black"
accent_color: "White"
frame_finish: "Matte"
frame_material: "Aluminum"
size: "Large"
wheel_size: "700c"
reward: 100
shield_529: "Unspecified"
theft_date: "2026-05-05 14:27"
theft_location: "San Francisco, CA 94102"
theft_location_details: "426 Fell St, San Francisco, CA 94102"
theft_description: "The bike was in our garage the day I bought it, and the thieves must have broken into our backyard and then left through the garage door."
contact_name: "Kian"
contact_email: "kiankyars@gmail.com"
contact_phone: "780-807-5819"
project529_url: "https://project529.com/garage/bikes/pannier-crank-aero-helmet/"
bike_index_url: ""
police_report_number: ""
low_price_threshold: 1200
reference_photos:
  - "bike.jpg"
  - "vélo.jpg"
distinctive_terms:
  - "cannondale"
  - "quick 5"
  - "quick"
  - "black"
  - "white"
  - "matte"
  - "large"
  - "hybrid"
  - "700c"
  - "aluminum"
