cadence: "twice_daily"
searches:
  - name: "OfferUp Cannondale"
    marketplace: "offerup"
    url: "https://offerup.com/search?q=cannondale"
  - name: "Craigslist SFBay Cannondale"
    marketplace: "craigslist"
    url: "https://sfbay.craigslist.org/search/bia?query=cannondale#search=2~gallery~0"
  - name: "Facebook Marketplace SF Cannondale"
    marketplace: "facebook"
    url: "https://www.facebook.com/marketplace/sanfrancisco/search/?query=cannondale"
  - name: "OfferUp Trek Fuel EX 7"
    marketplace: "offerup"
    url: "https://offerup.com/search?q=trek%20fuel%20ex%207"
  - name: "Craigslist SFBay Trek Fuel EX 7"
    marketplace: "craigslist"
    url: "https://sfbay.craigslist.org/search/bia?query=trek%20fuel%20ex%207#search=2~gallery~0"
  - name: "Facebook Marketplace SF Trek Fuel EX 7"
    marketplace: "facebook"
    url: "https://www.facebook.com/marketplace/sanfrancisco/search/?query=trek%20fuel%20ex%207"
