"""
Ordered waypoints for the Velo Journey 2026 "Frankfurt Loop".

Each segment is an ordered list of (label, geocode_query) pairs. The backbone
segments (EV15/EV17/EV7/EV6) list the real towns/junctions the official
EuroVelo route passes through, so that a cycle router (BRouter, trekking
profile on OSM data) following these waypoints hugs the signed EuroVelo line
(verified afterwards against OSM's route_bicycle_icn/ncn tags). EV8 is the
bespoke route the rider asked for; the connectors are routed the same way.

Direction of travel = order of the list. The end of one segment is the start
of the next (shared town) so the loop is continuous.
"""

SEGMENTS = [
    {
        "id": "ev15_rhine",
        "name": "EV15 Rhine + Mittelbuchen connector",
        "ev": "EV15",
        "desc": "Mittelbuchen -> Mainz (connector) then EuroVelo 15 up the Rhine to its Alpine source at Andermatt",
        "waypoints": [
            ("Mittelbuchen (Hanau)", "Mittelbuchen, Hanau, Germany"),
            ("Hanau", "Hanau, Germany"),
            ("Frankfurt am Main", "Frankfurt am Main, Germany"),
            ("Russelsheim", "Ruesselsheim am Main, Germany"),
            ("Mainz (join EV15)", "Mainz, Germany"),
            ("Oppenheim", "Oppenheim, Germany"),
            ("Worms", "Worms, Germany"),
            ("Ludwigshafen", "Ludwigshafen am Rhein, Germany"),
            ("Speyer", "Speyer, Germany"),
            ("Germersheim", "Germersheim, Germany"),
            ("Karlsruhe (Maxau)", "Karlsruhe, Germany"),
            ("Lauterbourg", "Lauterbourg, France"),
            ("Strasbourg", "Strasbourg, France"),
            ("Erstein", "Erstein, France"),
            ("Selestat", "Selestat, France"),
            ("Breisach", "Breisach am Rhein, Germany"),
            ("Neuenburg am Rhein", "Neuenburg am Rhein, Germany"),
            ("Basel", "Basel, Switzerland"),
            ("Rheinfelden", "Rheinfelden, Aargau, Switzerland"),
            ("Bad Saeckingen", "Bad Saeckingen, Germany"),
            ("Waldshut", "Waldshut-Tiengen, Germany"),
            ("Schaffhausen", "Schaffhausen, Switzerland"),
            ("Stein am Rhein", "Stein am Rhein, Switzerland"),
            ("Kreuzlingen (Bodensee)", "Kreuzlingen, Switzerland"),
            ("Rorschach", "Rorschach, Switzerland"),
            ("Buchs SG", "Buchs, St. Gallen, Switzerland"),
            ("Bad Ragaz", "Bad Ragaz, Switzerland"),
            ("Chur", "Chur, Switzerland"),
            ("Ilanz", "Ilanz, Switzerland"),
            ("Disentis", "Disentis, Switzerland"),
            ("Sedrun", "Sedrun, Switzerland"),
            ("Oberalppass", "Oberalppass, Switzerland"),
            ("Andermatt", "Andermatt, Switzerland"),
        ],
    },
    {
        "id": "ev17_rhone",
        "name": "EV17 Rhone (ViaRhona)",
        "ev": "EV17",
        "desc": "Andermatt over the Furka to the Rhone glacier, down the Valais and French Rhone to the Mediterranean",
        "waypoints": [
            ("Andermatt", "Andermatt, Switzerland"),
            ("Realp", "Realp, Switzerland"),
            ("Furkapass", "Furkapass, Switzerland"),
            ("Gletsch", "Gletsch, Switzerland"),
            ("Oberwald", "Oberwald, Wallis, Switzerland"),
            ("Fiesch", "Fiesch, Switzerland"),
            ("Brig", "Brig, Switzerland"),
            ("Visp", "Visp, Switzerland"),
            ("Sierre", "Sierre, Switzerland"),
            ("Sion", "Sion, Switzerland"),
            ("Martigny", "Martigny, Switzerland"),
            ("Saint-Maurice", "Saint-Maurice, Valais, Switzerland"),
            ("Le Bouveret", "Le Bouveret, Switzerland"),
            ("Saint-Gingolph", "Saint-Gingolph, France"),
            ("Evian-les-Bains", "Evian-les-Bains, France"),
            ("Thonon-les-Bains", "Thonon-les-Bains, France"),
            ("Geneva", "Geneva, Switzerland"),
            ("Seyssel", "Seyssel, Ain, France"),
            ("Belley", "Belley, France"),
            ("Lyon", "Lyon, France"),
            ("Vienne", "Vienne, Isere, France"),
            ("Valence", "Valence, Drome, France"),
            ("Montelimar", "Montelimar, France"),
            ("Pont-Saint-Esprit", "Pont-Saint-Esprit, France"),
            ("Avignon", "Avignon, France"),
            ("Arles", "Arles, France"),
            ("Port-Saint-Louis (Med)", "Port-Saint-Louis-du-Rhone, France"),
        ],
    },
    {
        "id": "ev8_med",
        "name": "EV8 Mediterranean (bespoke)",
        "ev": "EV8*",
        "desc": "Custom Mediterranean route: inland Provence (Manosque->Draguignan), French Riviera to Liguria, the Ligurian coast, over the Passo del Turchino to Piacenza",
        "waypoints": [
            ("Port-Saint-Louis", "Port-Saint-Louis-du-Rhone, France"),
            ("Arles", "Arles, France"),
            ("Salon-de-Provence", "Salon-de-Provence, France"),
            ("Aix-en-Provence", "Aix-en-Provence, France"),
            ("Manosque", "Manosque, France"),
            ("Greoux-les-Bains", "Greoux-les-Bains, France"),
            ("Riez", "Riez, France"),
            ("Quinson", "Quinson, France"),
            ("Aups", "Aups, France"),
            ("Salernes", "Salernes, France"),
            ("Draguignan", "Draguignan, France"),
            ("Le Muy", "Le Muy, France"),
            ("Frejus (coast)", "Frejus, France"),
            ("Cannes", "Cannes, France"),
            ("Antibes", "Antibes, France"),
            ("Nice", "Nice, France"),
            ("Monaco", "Monaco"),
            ("Menton", "Menton, France"),
            ("Ventimiglia", "Ventimiglia, Italy"),
            ("Sanremo", "Sanremo, Italy"),
            ("Imperia", "Imperia, Italy"),
            ("Albenga", "Albenga, Italy"),
            ("Savona", "Savona, Italy"),
            ("Varazze", "Varazze, Italy"),
            ("Genova Voltri", "Voltri, Genova, Italy"),
            ("Mele", "Mele, Genova, Italy"),
            ("Passo del Turchino", "Passo del Turchino, Italy"),
            ("Masone", "Masone, Genova, Italy"),
            ("Ovada", "Ovada, Italy"),
            ("Novi Ligure", "Novi Ligure, Italy"),
            ("Tortona", "Tortona, Italy"),
            ("Voghera", "Voghera, Italy"),
            ("Piacenza", "Piacenza, Italy"),
        ],
    },
    {
        "id": "ev7_central",
        "name": "EV7 Central Europe + Inn-valley connector",
        "ev": "EV7",
        "desc": "Piacenza across the Po plain to the EV7 corridor (Mantova-Verona), up the Adige and over the Brenner to Innsbruck, then the Inn valley to Passau",
        "waypoints": [
            ("Piacenza", "Piacenza, Italy"),
            ("Cremona", "Cremona, Italy"),
            ("Mantova (join EV7)", "Mantova, Italy"),
            ("Verona", "Verona, Italy"),
            ("Rovereto", "Rovereto, Italy"),
            ("Trento", "Trento, Italy"),
            ("Bolzano", "Bolzano, Italy"),
            ("Bressanone", "Bressanone, Italy"),
            ("Vipiteno", "Vipiteno, Italy"),
            ("Brennero (pass)", "Brennero, Italy"),
            ("Steinach am Brenner", "Steinach am Brenner, Austria"),
            ("Innsbruck", "Innsbruck, Austria"),
            ("Hall in Tirol", "Hall in Tirol, Austria"),
            ("Schwaz", "Schwaz, Austria"),
            ("Jenbach", "Jenbach, Austria"),
            ("Kufstein", "Kufstein, Austria"),
            ("Rosenheim", "Rosenheim, Germany"),
            ("Wasserburg am Inn", "Wasserburg am Inn, Germany"),
            ("Muehldorf am Inn", "Muehldorf am Inn, Germany"),
            ("Marktl", "Marktl, Germany"),
            ("Braunau am Inn", "Braunau am Inn, Austria"),
            ("Schaerding", "Schaerding, Austria"),
            ("Passau", "Passau, Germany"),
        ],
    },
    {
        "id": "ev6_danube",
        "name": "EV6 Danube + Main connector",
        "ev": "EV6",
        "desc": "EV6 up the Danube from Passau to Kelheim, the Main-Donau canal/Altmuehl to Nuremberg, then the Main downstream through Wuerzburg back to Mittelbuchen",
        "waypoints": [
            ("Passau", "Passau, Germany"),
            ("Vilshofen", "Vilshofen an der Donau, Germany"),
            ("Deggendorf", "Deggendorf, Germany"),
            ("Straubing", "Straubing, Germany"),
            ("Regensburg", "Regensburg, Germany"),
            ("Kelheim", "Kelheim, Germany"),
            ("Riedenburg", "Riedenburg, Germany"),
            ("Beilngries", "Beilngries, Germany"),
            ("Berching", "Berching, Germany"),
            ("Neumarkt", "Neumarkt in der Oberpfalz, Germany"),
            ("Nuremberg", "Nuremberg, Germany"),
            ("Fuerth", "Fuerth, Bavaria, Germany"),
            ("Erlangen", "Erlangen, Germany"),
            ("Forchheim", "Forchheim, Bavaria, Germany"),
            ("Bamberg", "Bamberg, Germany"),
            ("Schweinfurt", "Schweinfurt, Germany"),
            ("Wuerzburg", "Wuerzburg, Germany"),
            ("Karlstadt", "Karlstadt am Main, Germany"),
            ("Lohr am Main", "Lohr am Main, Germany"),
            ("Wertheim", "Wertheim, Germany"),
            ("Miltenberg", "Miltenberg, Germany"),
            ("Aschaffenburg", "Aschaffenburg, Germany"),
            ("Hanau", "Hanau, Germany"),
            ("Mittelbuchen (loop close)", "Mittelbuchen, Hanau, Germany"),
        ],
    },
]
